/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Damagree
 */
public class highscore extends javax.swing.JFrame {

    private Connection db ;
    DefaultTableModel mdl, mdl2, mdl3;
    public highscore() throws SQLException {
        initComponents();
        db = Conn.koneksiDB();
        String [] namajudul = {"NAMA", "SCORE"};
        mdl3 = new DefaultTableModel(namajudul,0);  
        tampilLevel1();
        tampilLevel2();
        tampilLevel3();
    }
    private void tampilLevel1(){
        try {
            mdl = new DefaultTableModel();
            mdl.addColumn("Name");
            mdl.addColumn("Score");
            Statement stmt = db.createStatement();
            ResultSet rs = stmt.executeQuery("select user.name,score.score from user,score where  score.id_user = user.id_user and level = 1 order by score desc");
            while (rs.next()){
                mdl.addRow(new Object[]{rs.getString(1),rs.getString(2)});
            }
            TABEL1.setModel(mdl);
            
            
        } catch (Exception e){
            
        }
    }
    private void tampilLevel2(){
        try {
            mdl2 = new DefaultTableModel();
            mdl2.addColumn("Name");
            mdl2.addColumn("Score");
            Statement stmt = db.createStatement();
            ResultSet rs = stmt.executeQuery("select user.name,score.score from user,score where  score.id_user = user.id_user and level = 2 order by score desc");
            while (rs.next()){
                mdl2.addRow(new Object[]{rs.getString(1),rs.getString(2)});
            }
            TABEL2.setModel(mdl2);
            
            
        } catch (Exception e){
            
        }
    }
    private void tampilLevel3(){
        try {
            mdl3 = new DefaultTableModel();
            mdl3.addColumn("Name");
            mdl3.addColumn("Score");
            Statement stmt = db.createStatement();
            ResultSet rs = stmt.executeQuery("select user.name,score.score from user,score where  score.id_user = user.id_user and level = 3 order by score desc");
            while (rs.next()){
                mdl3.addRow(new Object[]{rs.getString(1),rs.getString(2)});
            }
            TABEL3.setModel(mdl3);
            
            
        } catch (Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABEL1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABEL2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TABEL3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 1, 48)); // NOI18N
        jLabel1.setText("High Score");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        back.setBackground(new java.awt.Color(204, 204, 255));
        back.setFont(new java.awt.Font("Poppins SemiBold", 1, 11)); // NOI18N
        back.setText("Back To Menu");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));

        TABEL1.setBackground(new java.awt.Color(204, 204, 255));
        TABEL1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Score"
            }
        ));
        jScrollPane1.setViewportView(TABEL1);

        jTabbedPane1.addTab("level 1", jScrollPane1);

        TABEL2.setBackground(new java.awt.Color(204, 204, 0));
        TABEL2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NAME", "SCORE"
            }
        ));
        jScrollPane2.setViewportView(TABEL2);

        jTabbedPane1.addTab("level 2", jScrollPane2);

        TABEL3.setBackground(new java.awt.Color(255, 102, 153));
        TABEL3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NAME", "SCORE"
            }
        ));
        jScrollPane3.setViewportView(TABEL3);

        jTabbedPane1.addTab("level 3", jScrollPane3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 139, 574, 221));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sahara.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-910, -390, 1710, 920));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABEL1;
    private javax.swing.JTable TABEL2;
    private javax.swing.JTable TABEL3;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

   
   
}
