/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.sql.SQLException;
import java.util.logging.Logger;

/**
 *
 * @author Damagree
 */
public class Level extends javax.swing.JFrame {

    /**
     * Creates new form Level
     */
    public Level() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panellatar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        satu = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labellatar = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 1, 48)); // NOI18N
        jLabel1.setText("HIGH SCORE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panellatar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("OCR A Std", 3, 48)); // NOI18N
        jLabel2.setText("choose level");
        panellatar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        satu.setBackground(new java.awt.Color(204, 255, 204));
        satu.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        satu.setText("Beginner");
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        panellatar.add(satu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 150, 50));

        dua.setBackground(new java.awt.Color(255, 255, 153));
        dua.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        dua.setText("Medium");
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        panellatar.add(dua, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 150, 50));

        tiga.setBackground(new java.awt.Color(255, 0, 51));
        tiga.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        tiga.setText("Expert");
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        panellatar.add(tiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 151, 50));

        jButton1.setBackground(new java.awt.Color(153, 0, 102));
        jButton1.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panellatar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, -1, -1));

        labellatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lake.png"))); // NOI18N
        panellatar.add(labellatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panellatar, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
       Cookies.setLevel(1);
        try {
            new Level1().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_satuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
       Cookies.setLevel(2);
        try {
            new Level2().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_duaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        Cookies.setLevel(3);
        try {
            new Level3().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_tigaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dua;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labellatar;
    private javax.swing.JPanel panellatar;
    private javax.swing.JButton satu;
    private javax.swing.JButton tiga;
    // End of variables declaration//GEN-END:variables
}
