/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author Damagree
 */
public class Level1 extends javax.swing.JFrame {

    public Statement st;
    private int score = 0;
    private String namapemain;
    private boolean status1 = false;
    private boolean status2 = false;
     private Connection db;
     private ArrayList<String> listsoal = new ArrayList<>();
     private ArrayList<String> listjawaban = new ArrayList<>();
     int indexsoal = 0; 
    public String getNamapemain() {
        return namapemain;
    }

    public void setNamapemain(String namapemain) {
        this.namapemain = namapemain;
    }
    public Level1() throws SQLException {
 
        initComponents();
         db = Conn.koneksiDB();  
        nameplayer.setVisible(false);
        skorplayer.setVisible(false);
        soalnya.setVisible(false);
        jawab.setVisible(false);
        answer.setVisible(false);
        skorakhir.setVisible(false);
        selamat.setVisible(false);
        backmenu.setVisible(false);
        generateSoal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        answer = new javax.swing.JButton();
        jawab = new javax.swing.JTextField();
        soalnya = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        soal = new javax.swing.JLabel();
        nameplayer = new javax.swing.JLabel();
        pointtujuan = new javax.swing.JLabel();
        skorplayer = new javax.swing.JLabel();
        play = new javax.swing.JButton();
        good = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        selamat = new javax.swing.JLabel();
        skorakhir = new javax.swing.JLabel();
        backmenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        jLabel5.setFont(new java.awt.Font("VAGRounded BT", 0, 14)); // NOI18N
        jLabel5.setText("NAMA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 48, 12));

        answer.setText("Jawab");
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });

        soalnya.setBackground(new java.awt.Color(0, 0, 0));
        soalnya.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        soalnya.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(soalnya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jawab, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(answer)))
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(soalnya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jawab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 700, 90));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N

        soal.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        soal.setForeground(new java.awt.Color(255, 255, 255));
        soal.setText("SOAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(soal)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(soal))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));
        jPanel3.getAccessibleContext().setAccessibleName("");

        nameplayer.setFont(new java.awt.Font("Fira Sans Black", 1, 24)); // NOI18N
        nameplayer.setForeground(new java.awt.Color(255, 255, 255));
        nameplayer.setText("NAMA");
        jPanel1.add(nameplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        pointtujuan.setFont(new java.awt.Font("VAGRounded BT", 0, 18)); // NOI18N
        pointtujuan.setText("Beginner");
        jPanel1.add(pointtujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        skorplayer.setFont(new java.awt.Font("Fira Sans ExtraBold", 3, 36)); // NOI18N
        skorplayer.setText("SKOR  : 0");
        jPanel1.add(skorplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        play.setBackground(new java.awt.Color(126, 229, 207));
        play.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        play.setText("PLAY");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        jPanel1.add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        good.setFont(new java.awt.Font("Fira Sans SemiBold", 3, 48)); // NOI18N
        good.setText("Your Name");
        jPanel1.add(good, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 325, -1));

        selamat.setFont(new java.awt.Font("Altair", 3, 48)); // NOI18N
        selamat.setText("Selamat!");
        jPanel1.add(selamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 240, -1));

        skorakhir.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 48)); // NOI18N
        skorakhir.setText(".");
        jPanel1.add(skorakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 470, -1));

        backmenu.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        backmenu.setText("BACK TO MENU");
        backmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backmenuActionPerformed(evt);
            }
        });
        jPanel1.add(backmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/savana.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, -100, -1, 550));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backmenuActionPerformed
        new MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backmenuActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        Cookies.setName(name.getText());
     
        tampilSoal();
//setNamapemain(name.getText());
        nameplayer.setText(Cookies.getName());
        nameplayer.setVisible(true);
        skorplayer.setVisible(true);
        pointtujuan.setVisible(true);
        soal.setVisible(true);
        soalnya.setVisible(true);
        jawab.setVisible(true);
        answer.setVisible(true);
        play.setVisible(false);
        name.setVisible(false);
        good.setVisible(false);
        

    }//GEN-LAST:event_playActionPerformed

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        String jawaban = jawab.getText();
        if (listjawaban.get(indexsoal).equals(jawaban)){
            score+=100;
            indexsoal++;
            tampilSoal();
            
        } else {
            indexsoal++;
            tampilSoal();
        }
        jawab.setText("");
        
//        if(status1 == false && status2 == false){
//            if(jawab.getText().equalsIgnoreCase("Alexander Grahambell")){
//                JOptionPane.showMessageDialog(null, "BENAR");
//                poin+=10;
//                tambahskor();
//                pointplayer.setText("POIN  : "+poin);
//                skorplayer.setText("SKOR   : "+score);
//                jawab.setText("");
//                pointtujuan.setText("2");
//                soalnya.setText("7 + 7 + 77 x 0 - 7 : 7 = ...");
//                status1 =true;
//
//            }else if(!jawab.getText().equalsIgnoreCase("Jagung")){
//                JOptionPane.showMessageDialog(null, "SALAH");
//                poin -=10;
//                pointplayer.setText("POIN  : "+poin);
//                if(poin <= -50){
//                    JOptionPane.showMessageDialog(null, "GAME OVER");
//                    new MainMenu().setVisible(true);
//                    this.setVisible(false);
//                }
//            }
//        }
//
//        else if(status1 == true && status2 == false){
//            if(jawab.getText().equalsIgnoreCase("13")){
//                JOptionPane.showMessageDialog(null, "BENAR");
//                poin+=20;
//                tambahskor();
//                pointplayer.setText("POIN  : "+poin);
//                skorplayer.setText("SKOR   : "+score);
//                jawab.setText("");
//                pointtujuan.setText("3");
//                soalnya.setText("Nama lain zat hijau daun adalah...");
//                status2 =true;
//
//            }else if(!jawab.getText().equalsIgnoreCase("13")){
//                JOptionPane.showMessageDialog(null, "SALAH");
//                poin -=20;
//                pointplayer.setText("POIN  : "+poin);
//                if(poin <= -50){
//                    JOptionPane.showMessageDialog(null, "GAME OVER");
//                    new MainMenu().setVisible(true);
//                    this.setVisible(false);
//                }
//            }
//        }
//
//        else if(status2 == true && status1 == true){
//            if(jawab.getText().equalsIgnoreCase("klorofil") || jawab.getText().equalsIgnoreCase("Chlorophil")){
//                JOptionPane.showMessageDialog(null, "BENAR");
//                poin+=30;
//                tambahskor();
//                pointplayer.setText("POIN  : "+poin);
//                skorplayer.setText("SKOR   : "+score);
//                jawab.setText("");
//
//                skorakhir.setText("SKOR ANDA "+score);
//
//                nameplayer.setVisible(false);
//                skorplayer.setVisible(false);
//                pointtujuan.setVisible(false);
//                pointplayer.setVisible(false);
//                soal.setVisible(false);
//                soalnya.setVisible(false);
//                jawab.setVisible(false);
//                answer.setVisible(false);
//                skorakhir.setVisible(true);
//                selamat.setVisible(true);
//                backmenu.setVisible(true);
//                
//                try {
//                    Connection cn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/high score tubes", "root", "");
//                    cn.createStatement().executeUpdate("insert into highscore value('"
//                        + getNamapemain()+"','"
//                        + score+"')");
//                } catch (SQLException ex) {
//                    System.out.println(ex);
//                }
//                
//                
//                
//                
//            }else if(jawab.getText().equalsIgnoreCase("Chlorophil") || !jawab.getText().equalsIgnoreCase("klorofil")){
//                JOptionPane.showMessageDialog(null, "SALAH");
//                poin -=30;
//                pointplayer.setText("POIN  : "+poin);
//                if(poin <= -50){
//                    JOptionPane.showMessageDialog(null, "GAME OVER");
//                    new MainMenu().setVisible(true);
//                    this.setVisible(false);
//                }
//            }

       // }
    }//GEN-LAST:event_answerActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answer;
    private javax.swing.JButton backmenu;
    private javax.swing.JLabel good;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jawab;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameplayer;
    private javax.swing.JButton play;
    private javax.swing.JLabel pointtujuan;
    private javax.swing.JLabel selamat;
    private javax.swing.JLabel skorakhir;
    private javax.swing.JLabel skorplayer;
    private javax.swing.JLabel soal;
    private javax.swing.JLabel soalnya;
    // End of variables declaration//GEN-END:variables
//private void timerGame(){
//    Timer time = new Timer();
//    counter = 180;
//    TimerTask timerTask = new Timer Task(){
//    public void run(){
//        textWaktu.setText(Integer.toString(counter));
//        counter --;
//        if(counter == -1){
//            JOptionPane.showMessageDialog(rootPane, "Time's Up!");
//            timer.cancel;
//            new MainMenu().setVisible(true);
//            setVisible(false);
//        }
//    }
//};
//
//}
private void generateSoal(){
    try {
            Statement soal = db.createStatement();
            ResultSet hasil = soal.executeQuery("select * from question where level = 1 order by RAND() limit 15");
            while(hasil.next()){
                listsoal.add(hasil.getString("soal"));
                listjawaban.add(hasil.getString("jawaban"));
            }
} catch (Exception e){
        System.out.println("GS : "+e);
}
}
private void tampilSoal(){
    String soalskrg = listsoal.get(indexsoal);
    if (indexsoal == listsoal.size()-1) {
        nameplayer.setText(Cookies.getName());  
        nameplayer.setVisible(true);
        skorakhir.setText("Skor anda "+Integer.toString(+score));
        selamat.setVisible(true);
        skorakhir.setVisible(true);
        skorplayer.setVisible(false);
        backmenu.setVisible(true);
        answer.setVisible(false);
        try {
            Statement stmt = db.createStatement();
            stmt.execute("insert into user(name) values('"+Cookies.getName()+"')", Statement.RETURN_GENERATED_KEYS);
            ResultSet id = stmt.getGeneratedKeys();
            id.next();
            int iduser = id.getInt(1);
            stmt.execute("insert into score(id_user,score,level) Values("+iduser+","+score+",1)");
        } catch (Exception e){
            
        }
    } else {
        soalnya.setText(soalskrg);
        skorplayer.setText(Integer.toString(score));
        
    }
}
}
