/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt;

import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import pt.Check_in;
import pt.Check_in;
import pt.add_room;
import pt.add_room;
import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
/**
 *
 * @author 
 */
public class awal extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
int timerun=0;
    public awal() {
        initComponents();
        get_checkin();
        get_checkout();
        new Thread(){
            public void run(){
                while(timerun==0){
                    Calendar cal = Calendar.getInstance();
                    int hour = cal.getTime().getHours();
                    int minutes = cal.getTime().getMinutes();
                    int seconds = cal.getTime().getSeconds();
                    String str_hour    = hour+"";
                    String str_minutes = minutes+"";
                    String str_seceonds = seconds+"";
                    if(hour<10){
                        str_hour="0"+str_hour;
                    }
                    if(minutes<10){
                        str_minutes="0"+str_minutes;
                    }
                    if(seconds<10){
                        str_seceonds="0"+str_seceonds;
                    }
                    String time = str_hour+":"+str_minutes+":"+str_seceonds;
                    clock.setText(time);
                  
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_checkOut = new javax.swing.JTable();
        lihat_chekout = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_checkin = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        checkout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lihat_checkin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ceteakcheckin = new javax.swing.JButton();
        cetakcheckout = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        clock = new javax.swing.JLabel();
        addroom = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        room = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panel_checkin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        searchout = new javax.swing.JTextField();
        searchin = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(226, 106, 106));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel2.setText("RUMAH SAKIT BINA SEHAT  ");

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel3.setText("Jalan Buah Batu No.90, Malabar, Lengkong, Malabar, Lengkong, Kota Bandung, Jawa Barat 40262");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 130));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 490, 10));

        tabel_checkOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "    KAMAR ", "    TAGIHAN"
            }
        ));
        jScrollPane1.setViewportView(tabel_checkOut);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 470, 110));

        lihat_chekout.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lihat_chekout.setForeground(new java.awt.Color(214, 69, 65));
        lihat_chekout.setText("VIEW");
        lihat_chekout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihat_chekoutActionPerformed(evt);
            }
        });
        jPanel1.add(lihat_chekout, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 90, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 490, 16));

        tabel_checkin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "    KAMAR ", "    TAGIHAN"
            }
        ));
        jScrollPane2.setViewportView(tabel_checkin);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 470, 120));

        hapus.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        hapus.setForeground(new java.awt.Color(214, 69, 65));
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 610, 90, 30));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setText("LIST CHECK OUT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 230, 30));

        checkout.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        checkout.setForeground(new java.awt.Color(214, 69, 65));
        checkout.setText("CHECK OUT");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECK_OUT(evt);
            }
        });
        jPanel1.add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 140, 30));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setText("LIST CHECK IN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 230, 30));

        lihat_checkin.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lihat_checkin.setForeground(new java.awt.Color(214, 69, 65));
        lihat_checkin.setText("VIEW");
        lihat_checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihat_checkinActionPerformed(evt);
            }
        });
        jPanel1.add(lihat_checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 90, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 270, 40, 30));

        ceteakcheckin.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        ceteakcheckin.setForeground(new java.awt.Color(214, 69, 65));
        ceteakcheckin.setText("CETAK");
        ceteakcheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceteakcheckinActionPerformed(evt);
            }
        });
        jPanel1.add(ceteakcheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 100, 30));

        cetakcheckout.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cetakcheckout.setForeground(new java.awt.Color(214, 69, 65));
        cetakcheckout.setText("CETAK");
        cetakcheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakcheckoutActionPerformed(evt);
            }
        });
        jPanel1.add(cetakcheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 610, 90, 30));

        jPanel5.setBackground(new java.awt.Color(226, 106, 106));

        clock.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        addroom.setBackground(new java.awt.Color(255, 157, 157));
        addroom.setForeground(new java.awt.Color(102, 255, 204));
        addroom.setPreferredSize(new java.awt.Dimension(170, 160));
        addroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addroomMouseClicked(evt);
            }
        });

        room.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_Room_96px.png"))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel15.setText("ADD ROOM");

        javax.swing.GroupLayout addroomLayout = new javax.swing.GroupLayout(addroom);
        addroom.setLayout(addroomLayout);
        addroomLayout.setHorizontalGroup(
            addroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addroomLayout.createSequentialGroup()
                .addGroup(addroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addroomLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel7))
                    .addGroup(addroomLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(addroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addroomLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(73, Short.MAX_VALUE)))
        );
        addroomLayout.setVerticalGroup(
            addroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addroomLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(addroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addroomLayout.createSequentialGroup()
                    .addContainerGap(128, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)))
        );

        jPanel6.setBackground(new java.awt.Color(214, 69, 65));
        jPanel6.setForeground(new java.awt.Color(102, 255, 204));
        jPanel6.setPreferredSize(new java.awt.Dimension(170, 168));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_List_View_96px.png"))); // NOI18N

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel14.setText("LIST ROOM");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel8)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panel_checkin.setBackground(new java.awt.Color(255, 215, 189));
        panel_checkin.setForeground(new java.awt.Color(102, 255, 204));
        panel_checkin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_checkinMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_Key_2_96px.png"))); // NOI18N

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setText("CHECK IN");

        javax.swing.GroupLayout panel_checkinLayout = new javax.swing.GroupLayout(panel_checkin);
        panel_checkin.setLayout(panel_checkinLayout);
        panel_checkinLayout.setHorizontalGroup(
            panel_checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_checkinLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(panel_checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_checkinLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel4))))
        );
        panel_checkinLayout.setVerticalGroup(
            panel_checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_checkinLayout.createSequentialGroup()
                .addGroup(panel_checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_checkinLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel4))
                    .addGroup(panel_checkinLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(panel_checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(addroom, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(panel_checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addroom, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(209, 209, 209))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, 530));

        searchout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        searchout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchoutActionPerformed(evt);
            }
        });
        jPanel1.add(searchout, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 130, 30));

        searchin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        searchin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchinActionPerformed(evt);
            }
        });
        jPanel1.add(searchin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 130, 30));

        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, 30));

        jButton4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(214, 69, 65));
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setBounds(0, 0, 793, 742);
    }// </editor-fold>//GEN-END:initComponents

    private void lihat_chekoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihat_chekoutActionPerformed
            int row = tabel_checkOut.getSelectedRow();
        if(row!=-1){
            dispose();
           new Lihat_pasien1((String)tabel_checkOut.getValueAt(row, 2)).setVisible(true);
       }else{
            JOptionPane.showMessageDialog(null,"tidak ada baris yang dipilih !!!");
        }
    }//GEN-LAST:event_lihat_chekoutActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
         try{
        Class.forName("com.mysql.jdbc.Driver");
        
            String url ="jdbc:mysql://localhost/rumah_sakit";
            String user = "root";
            String pas =  "";
        Connection con = DriverManager.getConnection(url, user, pas);
        Statement stm = con.createStatement();
        int selected = tabel_checkOut.getSelectedRow();
        if(selected==-1){
            JOptionPane.showMessageDialog(null,"tidak ada baris yang dipilih !!!!");
        }
        
        stm.executeUpdate("delete from pasien  where id_customer='"+tabel_checkOut.getValueAt(selected,2)+"'");
            
        get_checkout();
     
      }catch(ClassNotFoundException | SQLException e){
          JOptionPane.showMessageDialog(null,"data gagal dihapus");
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void CHECK_OUT(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECK_OUT
       
      int rs  =tabel_checkin.getSelectedRow();
      String id =(String)tabel_checkin.getValueAt(rs, 2);
       dispose();
      new Checkout(id,this).setVisible(true);
    }//GEN-LAST:event_CHECK_OUT

    private void lihat_checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihat_checkinActionPerformed

       int row = tabel_checkin.getSelectedRow();
        if(row!=-1){
            dispose();
           new Lihat_pasien((String)tabel_checkin.getValueAt(row, 2)).setVisible(true);
       }else{
            JOptionPane.showMessageDialog(null,"tidak ada baris yang dipilih !!!");
        }
    }//GEN-LAST:event_lihat_checkinActionPerformed

    private void addroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addroomMouseClicked
        dispose();
        
        new add_room().setVisible(true);
    }//GEN-LAST:event_addroomMouseClicked

    private void panel_checkinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_checkinMouseClicked
         dispose();
        new Check_in().setVisible(true);
    }//GEN-LAST:event_panel_checkinMouseClicked

    private void ceteakcheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceteakcheckinActionPerformed
            FileOutputStream fileOut = null;
        try {
            TableModel tableModel = tabel_checkin.getModel();
            List<String> header = new ArrayList<String>();
            for (int i = 0; i < tableModel.getColumnCount(); i++) {
                header.add(tableModel.getColumnName(i));
            }
            List<List<Object>> data = new ArrayList<List<Object>>();
            for (int i = 0; i < tableModel.getRowCount(); i++) {
                List<Object> row = new ArrayList<Object>();
                for (int j = 0; j < tableModel.getColumnCount(); j++) {
                    row.add(tableModel.getValueAt(i, j));
                }
                data.add(row);
            }
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet sheet = workbook.createSheet();
            HSSFRow rowHeader = sheet.createRow(0);
            for (int i = 0; i < header.size(); i++) {
                HSSFCell rowCell = rowHeader.createCell(i);
                rowCell.setCellValue(header.get(i));
            }
            for (int i = 0; i < data.size(); i++) {
                HSSFRow row = sheet.createRow(i + 1);
                List<Object> dataRow = data.get(i);
                for (int j = 0; j < dataRow.size(); j++) {
                    HSSFCell cell = row.createCell(j);
                    cell.setCellValue(dataRow.get(j).toString());
                }
            }
            String tempFile = "D:\\ datacheckin.xls ";
            File fileTemp = new File(tempFile);
            if (fileTemp.exists()) {
                fileTemp.delete();
            }
            fileOut = new FileOutputStream(tempFile);
            workbook.write(fileOut);
            fileOut.close();
            Desktop.getDesktop().open(new File(tempFile));
        } catch (IOException ex) {
            Logger.getLogger(List_room.class.getName()).log(Level.SEVERE, null, ex);
       
        } finally {
            try {
                fileOut.close();
            } catch (IOException ex) {
                Logger.getLogger(List_room.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ceteakcheckinActionPerformed

    private void cetakcheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakcheckoutActionPerformed
             FileOutputStream fileOut = null;
        try {
            TableModel tableModel =tabel_checkOut.getModel();
            List<String> header = new ArrayList<String>();
            for (int i = 0; i < tableModel.getColumnCount(); i++) {
                header.add(tableModel.getColumnName(i));
            }
            List<List<Object>> data = new ArrayList<List<Object>>();
            for (int i = 0; i < tableModel.getRowCount(); i++) {
                List<Object> row = new ArrayList<Object>();
                for (int j = 0; j < tableModel.getColumnCount(); j++) {
                    row.add(tableModel.getValueAt(i, j));
                }
                data.add(row);
            }
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet sheet = workbook.createSheet();
            HSSFRow rowHeader = sheet.createRow(0);
            for (int i = 0; i < header.size(); i++) {
                HSSFCell rowCell = rowHeader.createCell(i);
                rowCell.setCellValue(header.get(i));
            }
            for (int i = 0; i < data.size(); i++) {
                HSSFRow row = sheet.createRow(i + 1);
                List<Object> dataRow = data.get(i);
                for (int j = 0; j < dataRow.size(); j++) {
                    HSSFCell cell = row.createCell(j);
                    cell.setCellValue(dataRow.get(j).toString());
                }
            }
            String tempFile = "D:\\ datachekout.xls ";
            File fileTemp = new File(tempFile);
            if (fileTemp.exists()) {
                fileTemp.delete();
            }
            fileOut = new FileOutputStream(tempFile);
            workbook.write(fileOut);
            fileOut.close();
            Desktop.getDesktop().open(new File(tempFile));
        } catch (IOException ex) {
            Logger.getLogger(List_room.class.getName()).log(Level.SEVERE, null, ex);
       
        } finally {
            try {
                fileOut.close();
            } catch (IOException ex) {
                Logger.getLogger(List_room.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cetakcheckoutActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
       new List_room().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void searchoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchoutActionPerformed

    private void searchinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchinActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel   md = new DefaultTableModel(row,0);
   
      try{
        String search = this.searchin.getText();
        Class.forName("com.mysql.jdbc.Driver");
        Class.forName("com.mysql.jdbc.Driver");
            String url ="jdbc:mysql://localhost/rumah_sakit";
            String user = "root";
            String pas =  "";
        Connection con = DriverManager.getConnection(url, user, pas);
        Statement stm = con.createStatement();
        ResultSet st=stm.executeQuery("select nomor_kamar,price,id_customer,nama,checkin,checkout from pasien where status_checkin='1' and nama like '%"+search+"%'");
        
         while(st.next()){
       
            
             
            md.addRow(new Object[]{st.getString(1),st.getString(2)+".Rp",st.getString("id_customer"),st.getString("nama"),st.getString("checkin"),st.getString("CHECKOUT")});
          
            
         }
         
         tabel_checkin.setModel(md);
     
      }catch(ClassNotFoundException | SQLException e){
          JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel   md = new DefaultTableModel(row,0);
   
      try{
        String search = this.searchout.getText();
        Class.forName("com.mysql.jdbc.Driver");
        Class.forName("com.mysql.jdbc.Driver");
            String url ="jdbc:mysql://localhost/rumah_sakit";
            String user = "root";
            String pas =  "";
        Connection con = DriverManager.getConnection(url, user, pas);
        Statement stm = con.createStatement();
        ResultSet st=stm.executeQuery("select nomor_kamar,price,id_customer,nama,checkin,checkout from pasien where status_checkin='0' and nama like '%"+search+"%'");
        
         while(st.next()){
       
            
             
            md.addRow(new Object[]{st.getString(1),st.getString(2)+".Rp",st.getString("id_customer"),st.getString("nama"),st.getString("checkin"),st.getString("CHECKOUT")});
          
            
         }
         
         tabel_checkOut.setModel(md);
     
      }catch(ClassNotFoundException | SQLException e){
          JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new awal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addroom;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cetakcheckout;
    private javax.swing.JButton ceteakcheckin;
    private javax.swing.JButton checkout;
    private javax.swing.JLabel clock;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton lihat_checkin;
    private javax.swing.JButton lihat_chekout;
    private javax.swing.JPanel panel_checkin;
    private javax.swing.JLabel room;
    private javax.swing.JTextField searchin;
    private javax.swing.JTextField searchout;
    private static javax.swing.JTable tabel_checkOut;
    private static javax.swing.JTable tabel_checkin;
    // End of variables declaration//GEN-END:variables

   static Object []row={"KAMAR","TAGIHAN","ID","NAMA","CHEKIN","CHECKOUT"}; 
  
   
   public static void get_checkin(){
  DefaultTableModel   md = new DefaultTableModel(row,0);
   
      try{
        Class.forName("com.mysql.jdbc.Driver");
        Class.forName("com.mysql.jdbc.Driver");
            String url ="jdbc:mysql://localhost/rumah_sakit";
            String user = "root";
            String pas =  "";
        Connection con = DriverManager.getConnection(url, user, pas);
        Statement stm = con.createStatement();
        ResultSet st=stm.executeQuery("select nomor_kamar,price,id_customer,nama,checkin,checkout from pasien where status_checkin='1'");
        
         while(st.next()){
       
            
             
            md.addRow(new Object[]{st.getString(1),st.getString(2)+".Rp",st.getString("id_customer"),st.getString("nama"),st.getString("checkin"),st.getString("CHECKOUT")});
          
            
         }
         
         tabel_checkin.setModel(md);
     
      }catch(ClassNotFoundException | SQLException e){
          JOptionPane.showMessageDialog(null,e);
        }
      }
   
   
   
   
   
      public  static void get_checkout(){
      DefaultTableModel   md1 = new DefaultTableModel(row,0);
      try{
        Class.forName("com.mysql.jdbc.Driver");
        
            String url ="jdbc:mysql://localhost/rumah_sakit";
            String user = "root";
            String pas =  "";
        Connection con = DriverManager.getConnection(url, user, pas);
        Statement stm = con.createStatement();
        ResultSet st=stm.executeQuery("select nomor_kamar,price,id_customer,nama,checkin,checkout from pasien where status_checkin='0'");
        
         while(st.next()){
       
            
             
            md1.addRow(new Object[]{st.getString(1),st.getString(2)+".Rp",st.getString("id_customer"),st.getString("nama"),st.getString("checkin"),st.getString("CHECKOUT")});
          
            
         }
         
         tabel_checkOut.setModel(md1);
     
      }catch(ClassNotFoundException | SQLException e){
          JOptionPane.showMessageDialog(null,e);
        }
      }
}
