/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tebakaku;

import com.sun.media.jfxmedia.events.PlayerEvent;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Layat
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    private Connection connection;
    public MainMenu() {
        initComponents();
        // Koneksi ke database
        connection = Config.databaseConnection();
        // Tampilan permainan menjadi ke tengah
        this.setLocationRelativeTo(null);
        // Gambar Pengaturan
        ImageIcon settingImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Image/settings.png")));
        Image settings = settingImage.getImage();
        Image imageScaled = settings.getScaledInstance(btnPengaturan.getWidth(), btnPengaturan.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon settingsImage = new ImageIcon(imageScaled);
        btnPengaturan.setIcon(settingsImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Mini = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        namaPemain = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        btnPermainanBaru = new javax.swing.JLabel();
        btnLanjutkanPermainan = new javax.swing.JLabel();
        btnSkorTertinggi = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JLabel();
        btnPengaturan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel2.setText("TEBAK AKU");

        Close.setBackground(new java.awt.Color(255, 255, 255));
        Close.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setText("x");
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        Mini.setBackground(new java.awt.Color(255, 255, 255));
        Mini.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        Mini.setText("-");
        Mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(149, 149, 149)
                .addComponent(Mini)
                .addGap(18, 18, 18)
                .addComponent(Close)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(137, 196, 244));

        namaPemain.setBackground(new java.awt.Color(255, 255, 255));
        namaPemain.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        namaPemain.setText("Siapakah Nama Kamu?");

        btnPermainanBaru.setBackground(new java.awt.Color(255, 255, 0));
        btnPermainanBaru.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnPermainanBaru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPermainanBaru.setText("Permainan Baru");
        btnPermainanBaru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPermainanBaru.setOpaque(true);
        btnPermainanBaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPermainanBaruMouseClicked(evt);
            }
        });

        btnLanjutkanPermainan.setBackground(new java.awt.Color(255, 255, 0));
        btnLanjutkanPermainan.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnLanjutkanPermainan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLanjutkanPermainan.setText("Lanjutkan Permainan");
        btnLanjutkanPermainan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLanjutkanPermainan.setOpaque(true);
        btnLanjutkanPermainan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLanjutkanPermainanMouseClicked(evt);
            }
        });

        btnSkorTertinggi.setBackground(new java.awt.Color(255, 255, 0));
        btnSkorTertinggi.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnSkorTertinggi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSkorTertinggi.setText("Skor Tertinggi");
        btnSkorTertinggi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSkorTertinggi.setOpaque(true);
        btnSkorTertinggi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSkorTertinggiMouseClicked(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(255, 51, 51));
        btnKeluar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnKeluar.setText("KELUAR");
        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluar.setOpaque(true);
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });

        btnPengaturan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/settings.png"))); // NOI18N
        btnPengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPengaturan.setMaximumSize(new java.awt.Dimension(10, 10));
        btnPengaturan.setMinimumSize(new java.awt.Dimension(5, 5));
        btnPengaturan.setPreferredSize(new java.awt.Dimension(10, 10));
        btnPengaturan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPengaturanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(namaPemain))
                                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLanjutkanPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPermainanBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSkorTertinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGap(0, 239, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(namaPemain)
                .addGap(18, 18, 18)
                .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPermainanBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLanjutkanPermainan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSkorTertinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
        //untuk menutup/meng-close landing page
        int dialogResult = JOptionPane.showConfirmDialog(this, "Kamu yakin mau keluar?");
        if(dialogResult == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_CloseMouseClicked

    private void MiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniMouseClicked
        // TODO add your handling code here:
        //untuk me-minimize landing page
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MiniMouseClicked

    private void btnPermainanBaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermainanBaruMouseClicked
        // TODO add your handling code here:
        if(inputNama.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Isi nama kamu dulu yaa :)");
        }else{
            String nama = inputNama.getText();
            try{
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery("SELECT * FROM temp_name WHERE nameUser = '"+nama+"'");
                resultSet.next();
                if(resultSet.getRow() == 1){
                    JOptionPane.showMessageDialog(this, "Nama kamu sudah digunakan orang lain nih, coba pakai nama yang lain ya :)");
                }else{
                    statement.execute("INSERT INTO temp_name (nameUser) VALUES ('"+nama+"')");
                    CookiesUser.setNamaUser(nama);
                    CookiesUser.setSkorTebakAku(0);
                    CookiesUser.setSkorTebakGambar(0);
                    CookiesUser.setSkorTebakAngka(0);
                    Menu menu = new Menu(nama);
                    menu.setVisible(true);
                    this.setVisible(false);
                }                
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btnPermainanBaruMouseClicked

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(this, "Kamu yakin mau keluar?");
        if(dialogResult == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarMouseClicked

    private void btnLanjutkanPermainanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLanjutkanPermainanMouseClicked
        // TODO add your handling code here:
        new LanjutkanPermainan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLanjutkanPermainanMouseClicked

    private void btnSkorTertinggiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSkorTertinggiMouseClicked
        // TODO add your handling code here:
        new SkorTertinggi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSkorTertinggiMouseClicked

    private void btnPengaturanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengaturanMouseClicked
        // TODO add your handling code here:
        String kataKunci = JOptionPane.showInputDialog(this, "Kata Kunci");
        if(kataKunci.equals("Admin Beng-Beng")){
            new AdminTebakAku().setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Gagal");
        }
    }//GEN-LAST:event_btnPengaturanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Mini;
    private javax.swing.JLabel btnKeluar;
    private javax.swing.JLabel btnLanjutkanPermainan;
    private javax.swing.JLabel btnPengaturan;
    private javax.swing.JLabel btnPermainanBaru;
    private javax.swing.JLabel btnSkorTertinggi;
    private javax.swing.JTextField inputNama;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel namaPemain;
    // End of variables declaration//GEN-END:variables
}
