/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psb;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lynn
 */
public class LihatNilai extends javax.swing.JFrame {
private Connection dbConnection;
    private koneksi db = new koneksi();
    private String bhs,inggris,mtk,ipa,total,rata,image,peminatan1,peminatan2;
    /**
     * Creates new form LihatNilai
     */
    public LihatNilai() {
        initComponents();
        data_nilai();
    }
    
    public void data_nilai(){
        db.dbConnection();
        try{
            String sql = "SELECT * FROM siswa_baru_nilai WHERE nisn = '" + UserSession.getNisn() +"'";
            Statement st = db.getConnection().createStatement();
            ResultSet rsUpdate = st.executeQuery(sql);
            while (rsUpdate.next()) {
//                namaUpdate,tempatlahirUpdate,tglLahirUpdate,jenisKelaminUpdate,noHpUpdate,image;
                bhs = rsUpdate.getString("nilai_bahasa");
                inggris = rsUpdate.getString("nilai_inggris");
                mtk = rsUpdate.getString("nilai_matematika");
                ipa = rsUpdate.getString("nilai_ipa");
                total = rsUpdate.getString("jumlah_nilai");
                rata = rsUpdate.getString("rata_rata");
                image = rsUpdate.getString("image_skhun");
                peminatan1 = rsUpdate.getString("peminatan_1");
                peminatan2 = rsUpdate.getString("peminatan_2");
                image = rsUpdate.getString("image_skhun");
//                u_id = rsLogin.getString("id_user");
//                System.out.println("data didapatkan");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        labelbhs.setText(bhs);
        labeling.setText(inggris);
        labelmtk.setText(mtk);
        labelipa.setText(ipa);
       
        ImageIcon icon = new ImageIcon(image);
        iniimage.setIcon(icon);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelbhs = new javax.swing.JLabel();
        iniimage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labeling = new javax.swing.JLabel();
        labelmtk = new javax.swing.JLabel();
        labelipa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btntdkditerima = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bahasa Indonesia");

        jLabel2.setText("Bahasa Inggris");

        jLabel3.setText("Matematika");

        jLabel4.setText("IPA");

        labelbhs.setText("jLabel6");

        iniimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniimage.setText("Foto SKHUN");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nilai");

        labeling.setText("jLabel8");

        labelmtk.setText("jLabel9");

        labelipa.setText("jLabel5");

        jButton1.setText("Diterima");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btntdkditerima.setText("Tidak Diterima");
        btntdkditerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntdkditerimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelbhs)
                                    .addComponent(labeling)
                                    .addComponent(labelmtk)
                                    .addComponent(labelipa))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btntdkditerima)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(58, 58, 58)))
                .addComponent(iniimage, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iniimage, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btntdkditerima))))
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelbhs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labeling))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelmtk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelipa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        db.dbConnection();
        String jurusan = UserSession.getJurusan();
        String status = "lulus";
        try{
            if (jurusan == "ipa") {
                String sql = "INSERT INTO hasil_seleksi (nisn,id_user,jurusan) "
                + "VALUES ('"+UserSession.getNisn()+ "','"+ UserSession.getU_id()+"','"+ jurusan +"')";
                Statement st = db.getConnection().createStatement();
                st.execute(sql);
                String updateSql = "UPDATE siswa_baru SET status = '"+status+"' WHERE nisn = '"+UserSession.getNisn()+"'";
                Statement stUpdate = db.getConnection().createStatement();
                stUpdate.execute(updateSql);
                new AdminSeleksi().setVisible(true);
                this.dispose();
            }else{
                String sql = "INSERT INTO hasil_seleksi (nisn,id_user,jurusan) "
                + "VALUES ('"+UserSession.getNisn()+ "','"+ UserSession.getU_id()+"','"+ jurusan +"')";
                Statement st = db.getConnection().createStatement();
                st.execute(sql);
                String updateSql = "UPDATE siswa_baru SET status = '"+status+"' WHERE nisn = '"+UserSession.getNisn()+"'";
                Statement stUpdate = db.getConnection().createStatement();
                stUpdate.execute(updateSql);
                new AdminSeleksi().setVisible(true);
                this.dispose();
            }
            
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btntdkditerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntdkditerimaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btntdkditerimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntdkditerima;
    private javax.swing.JLabel iniimage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelbhs;
    private javax.swing.JLabel labeling;
    private javax.swing.JLabel labelipa;
    private javax.swing.JLabel labelmtk;
    // End of variables declaration//GEN-END:variables
}
