/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psb;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Lynn
 */
public class LihatDataDiri extends javax.swing.JFrame {
    private Connection dbConnection;
    private koneksi db = new koneksi();
    String nisn;
    String namaUpdate,tempatlahirUpdate,jenisKelaminUpdate,noHpUpdate,image,ttl;
    Date tglLahirUpdate;
    String bb,tb,gd;
    String namaSekolah, alamatSekolah;

    /**
     * Creates new form LihatDataDiri
     */
    public LihatDataDiri() {
        initComponents();
        data_update_siswa();
//        System.out.println(UserSession.getNisn());
        data_update_jasmani();
        data_update_sekolah();
    }

     public void data_update_siswa(){
         db.dbConnection();
        try{
            String sql = "SELECT * FROM siswa_baru_data_diri WHERE nisn = '" + UserSession.getNisn() +"'";
            Statement st = db.getConnection().createStatement();
            ResultSet rsUpdate = st.executeQuery(sql);
            while (rsUpdate.next()) {
//                namaUpdate,tempatlahirUpdate,tglLahirUpdate,jenisKelaminUpdate,noHpUpdate,image;
                nisn = rsUpdate.getString("nisn");
                namaUpdate = rsUpdate.getString("nama_lengkap");
                tempatlahirUpdate = rsUpdate.getString("tempat_lahir");
                tglLahirUpdate = rsUpdate.getDate("tanggal_lahir");
                jenisKelaminUpdate = rsUpdate.getString("jenis_kelamin");
                image = rsUpdate.getString("image");
                ttl = tempatlahirUpdate+","+tglLahirUpdate;
                image = rsUpdate.getString("image");
                
//                u_id = rsLogin.getString("id_user");
//                System.out.println("data didapatkan");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        labelnisn.setText(nisn);
        labelNama.setText(namaUpdate);
        labelttl.setText(ttl);
        labeljeniskelamin.setText(jenisKelaminUpdate);
        ImageIcon icon = new ImageIcon(image);
        txtimage.setIcon(icon);
//        txtnisn.setText(UserSession.getNisn());
//        jXDatePicker1.setDate(UserDataDiri.getTgl_lahir());
//        txtnohp.setText(noHpUpdate);
//        String lokasi = UserDataDiri.getImage();
//        ImageIcon icon = new ImageIcon(lokasi);
//        inigambar.setIcon(icon);
    }
     
      private void data_update_jasmani(){
        
        try{
            String sql = "SELECT * FROM siswa_baru_ket_jasmani WHERE nisn = '" + UserSession.getNisn() +"'";
            Statement st = db.getConnection().createStatement();
            ResultSet rsUpdate = st.executeQuery(sql);
            while (rsUpdate.next()) {
//                namaUpdate,tempatlahirUpdate,tglLahirUpdate,jenisKelaminUpdate,noHpUpdate,image;
                bb = rsUpdate.getString("berat");
                tb = rsUpdate.getString("tinggi");
                gd = rsUpdate.getString("gol_darah");
//                u_id = rsLogin.getString("id_user");
//                System.out.println("data didapatkan");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        labelbb.setText(bb);
        labeltb.setText(tb);
        labelgoldar.setText(gd);
   
    }
     
    private void data_update_sekolah(){
        try{
            String sql = "SELECT * FROM siswa_baru_ket_pend_sblmnya WHERE nisn = '" + UserSession.getNisn() +"'";
            Statement st = db.getConnection().createStatement();
            ResultSet rsUpdate = st.executeQuery(sql);
            while (rsUpdate.next()) {
//                namaUpdate,tempatlahirUpdate,tglLahirUpdate,jenisKelaminUpdate,noHpUpdate,image;
                namaSekolah = rsUpdate.getString("asal_sekolah");
                alamatSekolah = rsUpdate.getString("alamat_sekolah");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        labelnamasekolah.setText(namaSekolah);
        labelalamat.setText(alamatSekolah);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelnisn = new javax.swing.JLabel();
        labelttl = new javax.swing.JLabel();
        labeljeniskelamin = new javax.swing.JLabel();
        labelbb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtimage = new javax.swing.JLabel();
        labeltb = new javax.swing.JLabel();
        labelgoldar = new javax.swing.JLabel();
        labelnamasekolah = new javax.swing.JLabel();
        labelalamat = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("NISN");

        jLabel4.setText("Tempat Tanggal Lahir");

        jLabel5.setText("Jenis Kelamin");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Data Diri");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Data Jasmani");

        jLabel7.setText("Berat Badan");

        jLabel8.setText("Tinggi Badan");

        jLabel9.setText("Gol Darah");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Asal Sekolah");

        jLabel11.setText("Nama Sekolah");

        jLabel12.setText("Alamat Sekolah");

        labelNama.setText("jLabel13");

        labelnisn.setText("jLabel13");

        labelttl.setText("jLabel13");

        labeljeniskelamin.setText("jLabel13");

        labelbb.setText("jLabel13");

        txtimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtimage, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtimage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labeltb.setText("jLabel13");

        labelgoldar.setText("jLabel14");

        labelnamasekolah.setText("jLabel13");

        labelalamat.setText("jLabel13");

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                                    .addComponent(labelnisn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labeljeniskelamin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelttl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labeltb, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelbb, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelgoldar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelnamasekolah)
                                    .addComponent(labelalamat))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(labelNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelnisn))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labelttl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(labeljeniskelamin))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(labelbb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(labeltb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(labelgoldar))))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelnamasekolah))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(labelalamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new LihatNilai().setVisible(true);
         this.dispose();
         
//            this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatDataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatDataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatDataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatDataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatDataDiri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelalamat;
    private javax.swing.JLabel labelbb;
    private javax.swing.JLabel labelgoldar;
    private javax.swing.JLabel labeljeniskelamin;
    private javax.swing.JLabel labelnamasekolah;
    private javax.swing.JLabel labelnisn;
    private javax.swing.JLabel labeltb;
    private javax.swing.JLabel labelttl;
    private javax.swing.JLabel txtimage;
    // End of variables declaration//GEN-END:variables
}
