/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;
import java.*;
import java.util.*;
import java.sql.*;
import javax.*;
import javax.swing.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MbahGenius
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    private Connection db;
    
    public login() throws SQLException{
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        ImageIcon settingImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Login.png")));
        Image login = settingImage.getImage();
        Image imageScaled = login.getScaledInstance(lb_icon.getWidth(), lb_icon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon settingsImage = new ImageIcon(imageScaled);
        lb_icon.setIcon(settingsImage);
        
        this.bt_masuk.setFont(new Font("Forte", Font.PLAIN, 33)); 
        this.bt_masuk.setForeground(Color.YELLOW);
        this.bt_masuk.setOpaque(false);
        this.bt_masuk.setContentAreaFilled(false);
        this.bt_masuk.setBorderPainted(false);
        this.bt_masuk.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        this.bt_daftar.setFont(new Font("Forte", Font.PLAIN, 33)); 
        this.bt_daftar.setForeground(Color.YELLOW);
        this.bt_daftar.setOpaque(false);
        this.bt_daftar.setContentAreaFilled(false);
        this.bt_daftar.setBorderPainted(false);
        this.bt_daftar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        fd_id.setOpaque(false);
        fd_id.setBackground(new java.awt.Color(255, 255, 255, 0));
        fd_pw.setOpaque(false);
        fd_pw.setBackground(new java.awt.Color(255, 255, 255, 0));
        


        db = (Connection) koneksi.koneksiDB();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_daftar = new javax.swing.JButton();
        fd_id = new javax.swing.JTextField();
        bt_masuk = new javax.swing.JButton();
        fd_pw = new javax.swing.JPasswordField();
        lb_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_daftar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 371, 240, 70));

        fd_id.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fd_id.setBorder(null);
        fd_id.setOpaque(false);
        fd_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fd_idActionPerformed(evt);
            }
        });
        getContentPane().add(fd_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 440, 80));
        fd_id.setOpaque(false);

        bt_masuk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_masuk.setOpaque(false);
        bt_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_masukActionPerformed(evt);
            }
        });
        getContentPane().add(bt_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 230, 70));

        fd_pw.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fd_pw.setBorder(null);
        getContentPane().add(fd_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 440, 80));

        lb_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/Login.png"))); // NOI18N
        lb_icon.setAutoscrolls(true);
        lb_icon.setPreferredSize(new java.awt.Dimension(1777, 1243));
        getContentPane().add(lb_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_masukActionPerformed
        // TODO add your handling code here:

        String u_id = null,u_pw = null, u_level = null;

        try {
            String sql = "SELECT * FROM user WHERE id_user = '" + fd_id.getText() + "' AND pw_user = '" + fd_pw.getText() + "'";
            Statement tsql = db.createStatement();
            ResultSet result=tsql.executeQuery(sql);

            if(result.next()){
                u_id = result.getString("id_user");
                u_pw = result.getString("pw_user");
                u_level = result.getString("level");

                if(result.getString("level").equals("admin")){
                    user_session.setU_id(u_id);
                    user_session.setU_pw(u_pw);
                    user_session.setU_level(u_level);

                    menu_admin fa = new menu_admin();
                    fa.show();
                    this.dispose();
                }else if(result.getString("level").equals("peminjam")){
                    user_session.setU_id(u_id);
                    user_session.setU_pw(u_pw);
                    user_session.setU_level(u_level);

                    menu_peminjam fu = new menu_peminjam();
                    fu.show();
                    this.dispose();
                }
            }else{
                String pilihan[]={"Daftar","Masuk lagi"};
                //                JOptionPane.showMessageDialog(null, "Maaf password atau username anda salah");
                int opsi = JOptionPane.showOptionDialog(null, "Maaf user belum terdaftar, apakah anda ingin mendaftar ?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                    null, pilihan, pilihan[0]);
                if(opsi == JOptionPane.YES_OPTION){
                    daftar df=new daftar();
                    df.show();
                    this.dispose();
                }else{
                    fd_id.setText("");
                    fd_pw.setText("");
                    fd_id.requestFocus();
                }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_bt_masukActionPerformed

    private void bt_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_daftarActionPerformed
        // TODO add your handling code here:
        daftar df = null;
        try {
            df = new daftar();
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        df.show();
        this.dispose();
    }//GEN-LAST:event_bt_daftarActionPerformed

    private void fd_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fd_idActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fd_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new login().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_daftar;
    private javax.swing.JButton bt_masuk;
    private javax.swing.JTextField fd_id;
    private javax.swing.JPasswordField fd_pw;
    private javax.swing.JLabel lb_icon;
    // End of variables declaration//GEN-END:variables
}
