/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisiran;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IRREGULER
 */
public class DataTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form LaporanTransaksi
     */
    Connection db;
    public DataTransaksi() throws SQLException {
        initComponents();
        db = new Koneksi().configDB();
        
        getData();
    }
    
    private void getData() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            
            model.addColumn("Kode Transaksi(Invoice)");
            model.addColumn("Tanggal");
            model.addColumn("Quantity");
            model.addColumn("Voucher");
            model.addColumn("Total (Rp)");
            Statement stmt = db.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT invoice.id_invoice, invoice.tgl_invoice, "
                    + "SUM(transaksi.quantity) AS jumlah, invoice.id_voucher, invoice.total FROM invoice, transaksi "
                    + "WHERE transaksi.id_invoice = invoice.id_invoice"
                    + " GROUP BY id_invoice");
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("id_invoice"),rs.getString("tgl_invoice"),rs.getString("jumlah"),
                rs.getString("id_voucher"),rs.getInt("total")});
                System.out.println(rs.getRow());
            }
            
            tabelTransaksi.setModel(model);
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        inputdata = new javax.swing.JLabel();
        datatransaksi = new javax.swing.JLabel();
        dataproduk = new javax.swing.JLabel();
        datavoucher = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Transaksi", "Tanggal", "Produk", "Quantity", "Voucher", "Total"
            }
        ));
        jScrollPane1.setViewportView(tabelTransaksi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 80, 650, 230);

        inputdata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputdataMouseClicked(evt);
            }
        });
        getContentPane().add(inputdata);
        inputdata.setBounds(40, 30, 170, 25);

        datatransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(datatransaksi);
        datatransaksi.setBounds(40, 80, 170, 20);

        dataproduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataproduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataprodukMouseClicked(evt);
            }
        });
        getContentPane().add(dataproduk);
        dataproduk.setBounds(40, 130, 180, 20);

        datavoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        datavoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datavoucherMouseClicked(evt);
            }
        });
        getContentPane().add(datavoucher);
        datavoucher.setBounds(40, 173, 170, 25);

        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(140, 270, 80, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Desain Data Transaksi.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 600);

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputdataMouseClicked
        this.dispose();
        try {
            new HeadOffice().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inputdataMouseClicked

    private void dataprodukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataprodukMouseClicked
        this.dispose();
        try {
            new DataProduk().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dataprodukMouseClicked

    private void datavoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datavoucherMouseClicked
        this.dispose();
        try {
            new DataVoucher().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_datavoucherMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Cookies.destroy();
        new Welcome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DataTransaksi().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataproduk;
    private javax.swing.JLabel datatransaksi;
    private javax.swing.JLabel datavoucher;
    private javax.swing.JLabel inputdata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JTable tabelTransaksi;
    // End of variables declaration//GEN-END:variables
}
