/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisiran;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IRREGULER
 */
public class DataProduk extends javax.swing.JFrame {

    /**
     * Creates new form DataProduk
     */
    Connection db;
    private int selectedRowTable = -1;
    public DataProduk() throws SQLException {
        initComponents();
        db = new Koneksi().configDB();
        
        this.setBackground(new Color(0,0,0,0));
        getData();
    }
    
    private void getData() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            
            model.addColumn("Kode");
            model.addColumn("Nama");
            model.addColumn("Jenis");
            model.addColumn("Harga");
            model.addColumn("Stok");
            Statement stmt = db.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM menu ORDER BY id_menu ASC");
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("id_menu"),rs.getString("nama"),rs.getString("jenis"),
                rs.getInt("harga"),rs.getInt("stok")});
            }
            tabelProduk.setModel(model);
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();
        textCari = new javax.swing.JTextField();
        inputdata = new javax.swing.JLabel();
        datatransaksi = new javax.swing.JLabel();
        dataproduk = new javax.swing.JLabel();
        datavoucher = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        pencarian = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Jenis", "Harga", "Stok"
            }
        ));
        tabelProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelProduk);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 120, 650, 210);

        textCari.setBorder(null);
        getContentPane().add(textCari);
        textCari.setBounds(770, 70, 130, 30);

        inputdata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputdataMouseClicked(evt);
            }
        });
        getContentPane().add(inputdata);
        inputdata.setBounds(40, 31, 177, 25);

        datatransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        datatransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datatransaksiMouseClicked(evt);
            }
        });
        getContentPane().add(datatransaksi);
        datatransaksi.setBounds(40, 78, 178, 25);

        dataproduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(dataproduk);
        dataproduk.setBounds(40, 126, 178, 25);

        datavoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        datavoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datavoucherMouseClicked(evt);
            }
        });
        getContentPane().add(datavoucher);
        datavoucher.setBounds(40, 173, 178, 25);

        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(145, 267, 70, 25);

        pencarian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pencarian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pencarianMouseClicked(evt);
            }
        });
        getContentPane().add(pencarian);
        pencarian.setBounds(927, 70, 25, 25);

        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(820, 355, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Desain Data Produk.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 600);

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputdataMouseClicked
        this.dispose();
        try {
            new HeadOffice().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DataProduk.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inputdataMouseClicked

    private void datatransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datatransaksiMouseClicked
        this.dispose();
        try {
            new DataTransaksi().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DataProduk.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_datatransaksiMouseClicked

    private void datavoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datavoucherMouseClicked
        this.dispose();
        try {
            new DataVoucher().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DataProduk.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_datavoucherMouseClicked

    private void pencarianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pencarianMouseClicked
        if (textCari.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap isi kotak pencarian");
        } else {
            tabelProduk.removeAll();
            DefaultTableModel model = new DefaultTableModel();
            
            model.addColumn("Kode");
            model.addColumn("Nama");
            model.addColumn("Jenis");
            model.addColumn("Harga");
            model.addColumn("Stok");
            
            String toSearch = textCari.getText();
            try {
                Statement stmt = db.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM menu WHERE nama LIKE '%"+toSearch+"%' "
                        + "ORDER BY id_menu ASC");
                while(rs.next()){
                    model.addRow(new Object[]{rs.getString("id_menu"),rs.getString("nama"),rs.getString("jenis"),
                    rs.getInt("harga"),rs.getInt("stok")});
                }
                tabelProduk.setModel(model);
            } catch (SQLException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_pencarianMouseClicked

    private void tabelProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelProdukMouseClicked
        int index = tabelProduk.getSelectedRow();
        selectedRowTable =index;
    }//GEN-LAST:event_tabelProdukMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        if (selectedRowTable >= 0) {
            try {
                String idMenu = tabelProduk.getValueAt(selectedRowTable, 0).toString();
                Statement stmt = db.createStatement();
                stmt.execute("DELETE FROM menu WHERE id_menu='"+idMenu+"'");
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                getData();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan : "+e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih tabel dulu");
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Cookies.destroy();
        new Welcome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DataProduk().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DataProduk.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataproduk;
    private javax.swing.JLabel datatransaksi;
    private javax.swing.JLabel datavoucher;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel inputdata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel pencarian;
    private javax.swing.JTable tabelProduk;
    private javax.swing.JTextField textCari;
    // End of variables declaration//GEN-END:variables
}
