/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisiran;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author IRREGULER
 */
public class Koki extends javax.swing.JFrame {

    /**
     * Creates new form Koki
     */
    Connection db;
    private int selectedRowTable = -1;
    public Koki() throws SQLException {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        db = new Koneksi().configDB();
        
        getData();
    }
    
    private void getData() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            
            model.addColumn("Kode Voucher");
            model.addColumn("Stok");
            model.addColumn("Potongan");
            Statement stmt = db.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT transaksi.id_transaksi, menu.nama, transaksi.quantity "
                    + "FROM transaksi, menu WHERE transaksi.id_menu = menu.id_menu AND "
                    + "status = 1 ORDER BY transaksi.id_transaksi ASC");
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("id_transaksi"),rs.getString("nama"),rs.getInt("quantity")});
            }
            tabelPesanan.setModel(model);
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPesanan = new javax.swing.JTable();
        daftarpesanan = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        selesai = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        tabelPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Transaksi", "Nama Makanan / Minuman", "Quantity"
            }
        ));
        tabelPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPesanan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 80, 650, 240);

        daftarpesanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(daftarpesanan);
        daftarpesanan.setBounds(38, 31, 180, 25);

        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(145, 267, 70, 25);

        selesai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selesaiMouseClicked(evt);
            }
        });
        getContentPane().add(selesai);
        selesai.setBounds(820, 355, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Desain Koki.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 600);

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPesananMouseClicked
        int index = tabelPesanan.getSelectedRow();
        selectedRowTable =index;
    }//GEN-LAST:event_tabelPesananMouseClicked

    private void selesaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selesaiMouseClicked
        if (selectedRowTable >= 0) {
            try {
                String idTransaksi = tabelPesanan.getValueAt(selectedRowTable, 0).toString();
                Statement stmt = db.createStatement();
                stmt.execute("UPDATE transaksi SET status=2 WHERE id_transaksi='"+idTransaksi+"'");
                JOptionPane.showMessageDialog(this, "Data berhasil diubah");
                getData();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan : "+e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih tabel dulu");
        }
    }//GEN-LAST:event_selesaiMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Cookies.destroy();
        new Welcome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Koki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Koki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Koki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Koki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Koki().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Koki.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private Color Color(int i, int i0, int i1, int i2) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daftarpesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel selesai;
    private javax.swing.JTable tabelPesanan;
    // End of variables declaration//GEN-END:variables
}
